In [229]:
import pandas as pd
import numpy as np

In [230]:
df = pd.read_csv("dataset/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       NaN       1   
2            3       NaN       3   
3            4       NaN       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282      NaN   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [231]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     887 non-null    float64
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          713 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         888 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [232]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [233]:
df.drop(["PassengerId","Name","Ticket","Cabin"],axis = 1,inplace=True)

In [234]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0.0       3    male  22.0      1      0   7.2500        S
1         NaN       1  female  38.0      1      0  71.2833        C
2         NaN       3  female   NaN      0      0      NaN        S
3         NaN       1  female  35.0      1      0  53.1000        S
4         0.0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886       0.0       2    male  27.0      0      0  13.0000        S
887       1.0       1  female  19.0      0      0  30.0000        S
888       0.0       3  female   NaN      1      2  23.4500        S
889       1.0       1    male  26.0      0      0  30.0000        C
890       0.0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [235]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [236]:
x = df.drop(columns = ["Survived"])
x

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female   NaN      0      0      NaN        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [237]:
y = df[["Survived"]]
y

Survived
0         0.0
1         NaN
2         NaN
3         NaN
4         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[891 rows x 1 columns]

In [238]:
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size = 0.2,train_size = 0.8)

In [239]:
x_train

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
454       3    male   NaN      0      0    8.0500        S
759       1  female  33.0      0      0   86.5000        S
856       1  female  45.0      1      1  164.8667        S
675       3    male  18.0      0      0    7.7750        S
815       1    male   NaN      0      0    0.0000        S
..      ...     ...   ...    ...    ...       ...      ...
610       3  female  39.0      1      5   31.2750        S
295       1    male   NaN      0      0   27.7208        C
339       1    male  45.0      0      0   35.5000        S
355       3    male  28.0      0      0    9.5000        S
810       3    male  26.0      0      0    7.8875        S

[712 rows x 7 columns]

In [240]:
x_test

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
846       3    male   NaN      8      2  69.5500        S
887       1  female  19.0      0      0  30.0000        S
631       3    male  51.0      0      0   7.0542        S
786       3  female  18.0      0      0   7.4958        S
880       2  female  25.0      0      1  26.0000        S
..      ...     ...   ...    ...    ...      ...      ...
250       3    male   NaN      0      0   7.2500        S
785       3    male  25.0      0      0   7.2500        S
304       3    male   NaN      0      0   8.0500        S
712       1    male  48.0      1      0  52.0000        S
718       3    male   NaN      0      0  15.5000        Q

[179 rows x 7 columns]

In [241]:
ytrain=y_train.to_numpy

In [242]:
ytrain

<bound method DataFrame.to_numpy of      Survived
454       0.0
759       1.0
856       1.0
675       0.0
815       0.0
..        ...
610       0.0
295       0.0
339       0.0
355       0.0
810       0.0

[712 rows x 1 columns]>

In [243]:
y_test

Survived
846       0.0
887       1.0
631       0.0
786       1.0
880       1.0
..        ...
250       0.0
785       0.0
304       0.0
712       1.0
718       0.0

[179 rows x 1 columns]

In [244]:
df.isnull().sum()

Survived      4
Pclass        0
Sex           0
Age         178
SibSp         0
Parch         0
Fare          3
Embarked      2
dtype: int64

In [245]:
df.dropna(subset = ["Survived","Fare","Embarked"],inplace = True)

In [246]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 883 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  883 non-null    float64
 1   Pclass    883 non-null    int64  
 2   Sex       883 non-null    object 
 3   Age       708 non-null    float64
 4   SibSp     883 non-null    int64  
 5   Parch     883 non-null    int64  
 6   Fare      883 non-null    float64
 7   Embarked  883 non-null    object 
dtypes: float64(3), int64(3), object(2)
memory usage: 62.1+ KB


In [247]:
df.sample()

Survived  Pclass     Sex   Age  SibSp  Parch    Fare Embarked
404       0.0       3  female  20.0      0      0  8.6625        S

In [248]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [249]:
tr = ColumnTransformer(transformers = [
    ('t1',SimpleImputer(),["Age"]),
    ('t2',OneHotEncoder(drop = "first",sparse=False),["Sex","Embarked"])
],remainder = "passthrough")

In [250]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('t1', SimpleImputer(), ['Age']),
                                ('t2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['Sex', 'Embarked'])])

In [251]:
trs = ColumnTransformer(transformers = [
    ('t1',SimpleImputer(),["Survived"])
],remainder = "passthrough")

In [252]:
s=trs.fit_transform(y_train)
s

array([[0.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.   

In [253]:
a=tr.fit_transform(x_train)
a

array([[ 29.84581882,   1.        ,   0.        , ...,   0.        ,
          0.        ,   8.05      ],
       [ 33.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  86.5       ],
       [ 45.        ,   0.        ,   0.        , ...,   1.        ,
          1.        , 164.8667    ],
       ...,
       [ 45.        ,   1.        ,   0.        , ...,   0.        ,
          0.        ,  35.5       ],
       [ 28.        ,   1.        ,   0.        , ...,   0.        ,
          0.        ,   9.5       ],
       [ 26.        ,   1.        ,   0.        , ...,   0.        ,
          0.        ,   7.8875    ]])

In [254]:
b=tr.fit_transform(x_test)
b

array([[29.11992806,  1.        ,  0.        , ...,  8.        ,
         2.        , 69.55      ],
       [19.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 30.        ],
       [51.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  7.0542    ],
       ...,
       [29.11992806,  1.        ,  0.        , ...,  0.        ,
         0.        ,  8.05      ],
       [48.        ,  1.        ,  0.        , ...,  1.        ,
         0.        , 52.        ],
       [29.11992806,  1.        ,  1.        , ...,  0.        ,
         0.        , 15.5       ]])

In [260]:
y_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 454 to 810
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  708 non-null    float64
dtypes: float64(1)
memory usage: 11.1 KB


In [256]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()