# exercise 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('dataset/bank-additional-full.csv')
df

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
41183       4963.6  yes  
41184       4963.6   no  
41185       4963.6   no  
41186       4963.6  yes  
41187       4963.6   no  

[41188 rows x 21 columns]

In [3]:
x=df.iloc[:,[10,0,11]]
y=df.iloc[:,20]

In [4]:
from sklearn.preprocessing import LabelEncoder
y=LabelEncoder().fit_transform(y)


In [5]:
y

array([0, 0, 0, ..., 0, 1, 0])

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [7]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
pred=lr.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [8]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,r2_score
confusion_matrix(y_test,pred)


array([[10823,   145],
       [ 1167,   222]], dtype=int64)

In [9]:
accuracy_score(y_test,pred)    

0.893825362142915

In [10]:
precision_score(y_test,pred,average='micro')

0.893825362142915

In [11]:
lr.score(x_train,y_train)

0.8929277513787243

In [12]:
lr.score(x_test,y_test)

0.893825362142915

# exercise 2

In [13]:
df=pd.read_csv('dataset/data_banknote_authentication.csv')
df.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [14]:
x=df.iloc[:,[0,1,2,3]]
y=df.iloc[:,-1]

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
lrc=LogisticRegression()
lrc.fit(x_train,y_train)
y_pred=lrc.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,r2_score
confusion_matrix(y_test,y_pred)

array([[146,   2],
       [  2, 125]], dtype=int64)

In [18]:
accuracy_score(y_test,y_pred)

0.9854545454545455

In [19]:
precision_score(y_test,y_pred)

0.984251968503937

In [20]:
r2_score(y_test,y_pred)

0.941476909980847