# Load numpy and check the version

In [1]:
import numpy as np
np.__version__

'1.21.5'

# creat a 1D array using array function

In [2]:
a=np.array([1,2,3,4,5])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3 4 5]
int32
(5,)


# create a 1D array using arange function

In [9]:
import numpy as np
a=np.arange(5)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2 3 4]
int32
(5,)


# create 2D array using array function

In [10]:
a=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(a)
print(a.dtype)
print(a.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
int32
(2, 5)


# create 2D array using arange function

In [6]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(a)
print(a.dtype)
print(a.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
int32
(3, 3)


# create 3D array using array function

In [8]:
import numpy as np
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a)
print(a.dtype)
print(a.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
int32
(3, 2, 2)


# create 3D array uning arange function

In [14]:
import numpy as np
a = np.arange(12).reshape(3,2,2)
print(a)
print(a.dtype)
print(a.shape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
int32
(3, 2, 2)


# creating array of once

In [15]:
import numpy as np
a = np.ones(5)
print(a)
print(a.dtype)
print(a.shape)

[1. 1. 1. 1. 1.]
float64
(5,)


In [16]:
import numpy as np
a=np.ones((2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


In [20]:
import numpy as np
a=np.ones((2,3,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
int32
(2, 3, 3)


# creating array of zeros

In [18]:
import numpy as np
a = np.zeros(5)
print(a)
print(a.dtype)
print(a.shape)

[0. 0. 0. 0. 0.]
float64
(5,)


In [21]:
import numpy as np
a=np.zeros((2,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[0 0 0]
 [0 0 0]]
int32
(2, 3)


In [26]:
import numpy as np
a=np.zeros((2,3,2),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
int32
(2, 3, 2)


# creating an array with random numbers

In [28]:
import numpy as np
a=np.random.randint(2,5,size=5)
print(a)
print(a.dtype)
print(a.shape)

[3 3 2 2 4]
int32
(5,)


In [29]:
import numpy as np
a=np.random.randint(5,size=(2,3))
print(a)
print(a.dtype)
print(a.shape)

[[1 4 4]
 [1 0 3]]
int32
(2, 3)


In [30]:
import numpy as np
a=np.random.randint(11,size=(3,2,3))
print(a)
print(a.dtype)
print(a.shape)

[[[ 2  5  3]
  [ 9  2  5]]

 [[ 4 10  3]
  [ 3  8  8]]

 [[ 8  1  1]
  [ 5  9  3]]]
int32
(3, 2, 3)


# creating random numbers with upper bond

In [31]:
import numpy as np
a=np.random.randint(5,[10,20,30,40])
print(a)
print(a.dtype)
print(a.shape)

[ 8 11 22  6]
int32
(4,)


In [32]:
import numpy as np
a=np.random.randint(6,[10,20,30],size=(2,3))
print(a)
print(a.dtype)
print(a.shape)

[[ 9 10 22]
 [ 7 11 29]]
int32
(2, 3)


# creating random numbers with lower bond

In [35]:
import numpy as np
a=np.random.randint([5,8,6],10)
print(a)
print(a.dtype)
print(a.shape)

[6 8 7]
int32
(3,)


In [37]:
import numpy as np
a=np.random.randint([7,8,9],10,size=(2,3))
print(a)
print(a.dtype)
print(a.shape)

[[9 8 9]
 [8 9 9]]
int32
(2, 3)


# creating random number with multiple low and multiple high

In [39]:
import numpy as np
a=np.random.randint((5,6,7),(7,8,9))
print(a)
print(a.dtype)
print(a.shape)

[6 6 8]
int32
(3,)


In [40]:
import numpy as np
a=np.random.randint((4,5,6),(7,8,9),size=(2,3))
print(a)
print(a.dtype)
print(a.shape)

[[6 6 6]
 [5 6 6]]
int32
(2, 3)


# random randn and rand and randint functions

In [5]:
import numpy as np
a=np.random.randn(3)
print(a)
print(a.dtype)
print(a.shape)

[ 0.56288048 -0.02272142  0.91380158]
float64
(3,)


In [6]:
import numpy as np
a=np.random.randn(2,3)
print(a)
print(a.dtype)
print(a.shape)

[[-0.99614034 -0.07153738  0.33470551]
 [-0.19136866 -1.2465513   1.04058869]]
float64
(2, 3)


In [7]:
import numpy as np
a=np.random.randn(3,2,3)
print(a)
print(a.dtype)
print(a.shape)

[[[-0.52009277 -1.3287032  -1.02319004]
  [-1.09037156 -0.73566337  2.78378839]]

 [[-1.47217409 -0.54863416 -0.80186784]
  [-0.50432228  1.71130264  0.0176463 ]]

 [[-1.56125523  0.84674486  0.15159255]
  [ 0.34161482  1.29872641 -1.49278467]]]
float64
(3, 2, 3)


In [9]:
import numpy as np
a=np.random.rand(2,3)
print(a)

[[0.29204441 0.2314328  0.02507253]
 [0.68900383 0.195917   0.88105462]]


In [10]:
import numpy as np
a=np.random.randint(2,3)
print(a)

2


# array indexing

In [14]:
import numpy as np
a=np.array([2,3,4,5])
print(a[1])

3


In [17]:
import numpy as np
a=np.array([[2,3,4,5],[5,6,7,8]])
print(a[1,2])

7


In [19]:
import numpy as np
a=np.array([[[1,2,6],[3,4,2]],[[5,6,4],[7,8,9]]])
print(a[0,1,1])

4


In [20]:
import numpy as np
a=np.array([2,3,4,5])
print(a[-2])

4


In [21]:
import numpy as np
a=np.array([[2,3,4,5],[5,6,7,8]])
print(a[-2,-3])

3


In [22]:
import numpy as np
a=np.array([[[1,2,6],[3,4,2]],[[5,6,4],[7,8,9]]])
print(a[-1,-2,-3])


5


In [23]:
import numpy as np
a=np.array([[[1,2,6],[3,4,2]],[[5,6,4],[7,8,9]]])
print(a[-1,1,-2])

8


# numpy slicing

In [27]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[1:5])

[2 3 4 5]


In [29]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[4:])

[5 6 7]


In [30]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[:4])

[1 2 3 4]


# negative slicing

In [31]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[-3:-1])

[5 6]


In [32]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[1:5:2])

[2 4]


In [37]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[::2])

[1 3 5 7]


# slicing 2D array

In [39]:
import numpy as np
a=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(a[1,1:4])

[6 7 8]


In [40]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,2])

[3 8]


In [41]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# Numpy Array copy vs View

# COPY

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
a=np.copy(arr)
arr[2]=6
print(arr)
print(a)

[1 2 6 4 5]
[1 2 3 4 5]


# VIEW

In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a.view()
a[2]=9
print(a)
print(b)

[1 2 9 4 5]
[1 2 9 4 5]


# RESHAPING

In [10]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
b=a.reshape([5,2])
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [11]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
b=a.reshape([2,6])
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
b=a.reshape([2,3,2])
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# SUM() FUNCTION

In [15]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(np.sum(a,axis=0))

[1 2 3 4]
10


In [17]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.sum(a,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
[ 6  8 10 12]


In [18]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.sum(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[10 26]


In [19]:
import numpy as np
a=np.array([[[1,2,3,4]],[[5,6,7,8]],[[9,10,11,12]]])
print(a)
print(np.sum(a,axis=0))

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
[[15 18 21 24]]


In [22]:
import numpy as np
a=np.array([[[1,2,3,4]],[[5,6,7,8]],[[9,10,11,12]]])
print(a)
print(np.sum(a))

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
78


# MEAN

In [26]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.mean(a))

[[1 2 3 4]
 [5 6 7 8]]
4.5


In [27]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.mean(a,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
[3. 4. 5. 6.]


In [28]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.mean(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[2.5 6.5]


# STANDARD DEVIATION

In [29]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.std(a))

[[1 2 3 4]
 [5 6 7 8]]
2.29128784747792


In [30]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.std(a,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
[2. 2. 2. 2.]


In [31]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.std(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[1.11803399 1.11803399]


# VARIANCE

In [32]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.var(a))

[[1 2 3 4]
 [5 6 7 8]]
5.25


In [33]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.var(a,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
[4. 4. 4. 4.]


In [34]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.var(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[1.25 1.25]


min

In [35]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a))

[[1 2 3 4]
 [5 6 7 8]]
1


In [36]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]


In [37]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[1 5]


max

In [38]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.max(a))

[[1 2 3 4]
 [5 6 7 8]]
8


In [39]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.max(a,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]


In [40]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.max(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[4 8]
