# Pandas Series

In [6]:
import numpy as np
import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)
a=pd.Series(['a','b','c','d','e'])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object


In [7]:
import pandas as pd
score=pd.Series([12,34,56,78,90,1,2,3,4,5,6])
print(score)

0     12
1     34
2     56
3     78
4     90
5      1
6      2
7      3
8      4
9      5
10     6
dtype: int64


In [10]:
import pandas as pd
i=pd.Index(['rohit','rahul','virat','sky','dk','axar','hardik','ashwin','arshdeep','chahal','kumar'])
score=pd.Series([12,34,56,78,90,1,2,3,4,5,6],index=i)
print(score)

rohit       12
rahul       34
virat       56
sky         78
dk          90
axar         1
hardik       2
ashwin       3
arshdeep     4
chahal       5
kumar        6
dtype: int64


# DATAFRAMES

In [1]:
import numpy as np
import pandas as pd
arr=np.arange(0,9).reshape(3,3)
print(arr)  #numpy ndarray
df=pd.DataFrame(arr,index=['a','b','c'],columns=['A','B','C'])
print(df)   #pandas data frame

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [2]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[23,24,20,19],[20,24,25,19],[19,22,23,18]],index=['rahul','krishna','abhinav'],columns=['OSA','python','SE','Java'])
print(df)

         OSA  python  SE  Java
rahul     23      24  20    19
krishna   20      24  25    19
abhinav   19      22  23    18


In [3]:
import numpy as np
import pandas as pd
ser1=pd.Series([23,20,19])
ser2=pd.Series([20,23,25,20])
print(pd.DataFrame({"OSA":ser1,"python":ser2}))

    OSA  python
0  23.0      20
1  20.0      23
2  19.0      25
3   NaN      20


# Create DataFrame containing information about cities

In [4]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
#print(i)
pop=pd.Series(['6.72','12.54','7.0'],index=i, name="Population")
#print(pop)
cap=pd.Series(['Banglore','Mumbai','Gandhinagar'],index=i, name="Capital")
#print(cap)
#df=pd.DataFrame ([pop,cap])    #will not display in prpoer format
#df=pd.DataFrame ([pop,cap]).T  #will display in proper format but columns names missing
df=pd.DataFrame({"Population":pop, "Capital":cap})
#df=pd.DataFrame([['6.72','Banglore'],[.12.54,'Mumbai'],['7.0','Gandhinagar']],index=["Karnataka","Maharashtra","Gandhinagar"],columns=['Population','Capital'])#creating dataframe in one line
print(df)

            Population      Capital
Karnataka         6.72     Banglore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar


# how to add new data to series

In [5]:
import numpy as np
import pandas as pd
#print(pop)
pop.append(pd.Series({"TamilNadu":8.9}))
#print(pop)

#hoe to add new data to series

C:\Users\CS-L2-PC04\AppData\Local\Temp\ipykernel_5648\2795845560.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pop.append(pd.Series({"TamilNadu":8.9}))


Karnataka       6.72
Maharashtra    12.54
Gujarat          7.0
TamilNadu        8.9
dtype: object

# how to add new data to series

Method 1

In [6]:
import numpy as np
import pandas as pd
df=pd.DataFrame([['6.72','Banglore'],['12.54','Mumbai'],['7.0','Gandhinagar']],index=['Karnataka','Maharashtra','Gujarat'],columns=['Population','Capitals'])
#print(df)
print(df.append(pd.DataFrame([['8.9','chennai'],['12.54','Hyderabad']],index=['Tamil Nadu','Andra Pradesh'],columns=['Population','Capital'])))

              Population     Capitals    Capital
Karnataka           6.72     Banglore        NaN
Maharashtra        12.54       Mumbai        NaN
Gujarat              7.0  Gandhinagar        NaN
Tamil Nadu           8.9          NaN    chennai
Andra Pradesh      12.54          NaN  Hyderabad


C:\Users\CS-L2-PC04\AppData\Local\Temp\ipykernel_5648\4280477132.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([['8.9','chennai'],['12.54','Hyderabad']],index=['Tamil Nadu','Andra Pradesh'],columns=['Population','Capital'])))


method 2

In [9]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.0'],index=i, name="Capital")
cap=pd.Series(['Banglore','Mumbai','Gandhinagar'],index=i, name="Capital")
df=pd.DataFrame({"Population":pop,"Capital":cap})
print(df)
print(df.append(pd.DataFrame({"Population":pd.Series({"Tamil Nadu":8.9, "Andra Pradesh":12.6}),"Capital":pd.Series({"Tamil Nadu":"Chennai","Andra Pradesh":"Hyderabad"})})))

            Population      Capital
Karnataka         6.72     Banglore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar
              Population      Capital
Karnataka           6.72     Banglore
Maharashtra        12.54       Mumbai
Gujarat              7.0  Gandhinagar
Tamil Nadu           8.9      Chennai
Andra Pradesh       12.6    Hyderabad


C:\Users\CS-L2-PC04\AppData\Local\Temp\ipykernel_5648\2158490925.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"Population":pd.Series({"Tamil Nadu":8.9, "Andra Pradesh":12.6}),"Capital":pd.Series({"Tamil Nadu":"Chennai","Andra Pradesh":"Hyderabad"})})))
