# Pandas Series

In [6]:
import numpy as np
import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)
a=pd.Series(['a','b','c','d','e'])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object


In [7]:
import pandas as pd
score=pd.Series([12,34,56,78,90,1,2,3,4,5,6])
print(score)

0     12
1     34
2     56
3     78
4     90
5      1
6      2
7      3
8      4
9      5
10     6
dtype: int64


In [10]:
import pandas as pd
i=pd.Index(['rohit','rahul','virat','sky','dk','axar','hardik','ashwin','arshdeep','chahal','kumar'])
score=pd.Series([12,34,56,78,90,1,2,3,4,5,6],index=i)
print(score)

rohit       12
rahul       34
virat       56
sky         78
dk          90
axar         1
hardik       2
ashwin       3
arshdeep     4
chahal       5
kumar        6
dtype: int64


# DATAFRAMES

In [1]:
import numpy as np
import pandas as pd
arr=np.arange(0,9).reshape(3,3)
print(arr)  #numpy ndarray
df=pd.DataFrame(arr,index=['a','b','c'],columns=['A','B','C'])
print(df)   #pandas data frame

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [2]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[23,24,20,19],[20,24,25,19],[19,22,23,18]],index=['rahul','krishna','abhinav'],columns=['OSA','python','SE','Java'])
print(df)

         OSA  python  SE  Java
rahul     23      24  20    19
krishna   20      24  25    19
abhinav   19      22  23    18


In [3]:
import numpy as np
import pandas as pd
ser1=pd.Series([23,20,19])
ser2=pd.Series([20,23,25,20])
print(pd.DataFrame({"OSA":ser1,"python":ser2}))

    OSA  python
0  23.0      20
1  20.0      23
2  19.0      25
3   NaN      20


# Create DataFrame containing information about cities

In [4]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
#print(i)
pop=pd.Series(['6.72','12.54','7.0'],index=i, name="Population")
#print(pop)
cap=pd.Series(['Banglore','Mumbai','Gandhinagar'],index=i, name="Capital")
#print(cap)
#df=pd.DataFrame ([pop,cap])    #will not display in prpoer format
#df=pd.DataFrame ([pop,cap]).T  #will display in proper format but columns names missing
df=pd.DataFrame({"Population":pop, "Capital":cap})
#df=pd.DataFrame([['6.72','Banglore'],[.12.54,'Mumbai'],['7.0','Gandhinagar']],index=["Karnataka","Maharashtra","Gandhinagar"],columns=['Population','Capital'])#creating dataframe in one line
print(df)

            Population      Capital
Karnataka         6.72     Banglore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar


# how to add new data to series

In [5]:
import numpy as np
import pandas as pd
#print(pop)
pop.append(pd.Series({"TamilNadu":8.9}))
#print(pop)

#hoe to add new data to series

C:\Users\CS-L2-PC04\AppData\Local\Temp\ipykernel_5648\2795845560.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pop.append(pd.Series({"TamilNadu":8.9}))


Karnataka       6.72
Maharashtra    12.54
Gujarat          7.0
TamilNadu        8.9
dtype: object

# how to add new data to series

Method 1

In [6]:
import numpy as np
import pandas as pd
df=pd.DataFrame([['6.72','Banglore'],['12.54','Mumbai'],['7.0','Gandhinagar']],index=['Karnataka','Maharashtra','Gujarat'],columns=['Population','Capitals'])
#print(df)
print(df.append(pd.DataFrame([['8.9','chennai'],['12.54','Hyderabad']],index=['Tamil Nadu','Andra Pradesh'],columns=['Population','Capital'])))

              Population     Capitals    Capital
Karnataka           6.72     Banglore        NaN
Maharashtra        12.54       Mumbai        NaN
Gujarat              7.0  Gandhinagar        NaN
Tamil Nadu           8.9          NaN    chennai
Andra Pradesh      12.54          NaN  Hyderabad


C:\Users\CS-L2-PC04\AppData\Local\Temp\ipykernel_5648\4280477132.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([['8.9','chennai'],['12.54','Hyderabad']],index=['Tamil Nadu','Andra Pradesh'],columns=['Population','Capital'])))


method 2

In [9]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.0'],index=i, name="Capital")
cap=pd.Series(['Banglore','Mumbai','Gandhinagar'],index=i, name="Capital")
df=pd.DataFrame({"Population":pop,"Capital":cap})
print(df)
print(df.append(pd.DataFrame({"Population":pd.Series({"Tamil Nadu":8.9, "Andra Pradesh":12.6}),"Capital":pd.Series({"Tamil Nadu":"Chennai","Andra Pradesh":"Hyderabad"})})))

            Population      Capital
Karnataka         6.72     Banglore
Maharashtra      12.54       Mumbai
Gujarat            7.0  Gandhinagar
              Population      Capital
Karnataka           6.72     Banglore
Maharashtra        12.54       Mumbai
Gujarat              7.0  Gandhinagar
Tamil Nadu           8.9      Chennai
Andra Pradesh       12.6    Hyderabad


C:\Users\CS-L2-PC04\AppData\Local\Temp\ipykernel_5648\2158490925.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"Population":pd.Series({"Tamil Nadu":8.9, "Andra Pradesh":12.6}),"Capital":pd.Series({"Tamil Nadu":"Chennai","Andra Pradesh":"Hyderabad"})})))


# concat new column to dataframe

In [2]:
import numpy as np
import pandas as pd
i=pd.Index(['Karnataka','Maharashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.8'],index=i,name='Population')
cap=pd.Series(['Banglore','mumbai','Gandinagar'],index=i, name='Capital')
df=pd.DataFrame({'Population':pop,'Capital':cap})
#print(df)
df1=pd.concat(
        [df,pd.DataFrame({
                            'Area':pd.Series(['2.1','3.1','5.5'],index=pop.index),
                            'CM':pd.Series(['Bomai','Shinde','xyz'],index=pop.index)
                        })
        ], axis=1
    )
df1.to_csv('cities.csv')
print(df1)


            Population     Capital Area      CM
Karnataka         6.72    Banglore  2.1   Bomai
Maharashtra      12.54      mumbai  3.1  Shinde
Gujarat            7.8  Gandinagar  5.5     xyz


# subsetting

In [3]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [4]:
srs = Series(np.arange(5), index=["alpha","beta","gama","delta","elipson"])
srs

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32

In [5]:
srs[:2]

alpha    0
beta     1
dtype: int32

In [6]:
srs[["beta","delta"]]

beta     1
delta    3
dtype: int32

In [7]:
srs["beta":"delta"]

beta     1
gama     2
delta    3
dtype: int32

In [8]:
print(srs)
srs[srs > 3]

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32


elipson    4
dtype: int32

In [9]:
srs > 3

alpha      False
beta       False
gama       False
delta      False
elipson     True
dtype: bool

In [10]:
srs2 = Series(["zero","one","two","three","four"], index=[3,2,4,0,1])
srs2

3     zero
2      one
4      two
0    three
1     four
dtype: object

In [11]:
srs2[2:4]    

4      two
0    three
dtype: object

In [12]:
srs2.iloc[1:4]

2      one
4      two
0    three
dtype: object

In [13]:
srs2.loc[3:0]

3     zero
2      one
4      two
0    three
dtype: object

In [14]:
df = DataFrame(np.arange(21).reshape(7,3), columns=['AAA','BBB','CCC'], index=["alpha","beta","gama","delta","epsilon","zeta","eta"])
df

AAA  BBB  CCC
alpha      0    1    2
beta       3    4    5
gama       6    7    8
delta      9   10   11
epsilon   12   13   14
zeta      15   16   17
eta       18   19   20

In [15]:
df.AAA

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [16]:
df['AAA']

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [17]:
df[['BBB','CCC']]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [18]:
df.iloc[1:3, 1:2]

BBB
beta    4
gama    7

In [19]:
df.loc['beta':'delta', 'BBB':'CCC']

BBB  CCC
beta     4    5
gama     7    8
delta   10   11

In [20]:
df.iloc[:, 1:3]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [21]:
df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']]

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [22]:
df2 = df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']].copy()
df2

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [23]:
df2['CCC'] = Series({'alpha':11, 'gama':18, 'zeta':5})
df2

BBB  CCC
alpha    1   11
gama     7   18
zeta    16    5

In [24]:
df2.iloc[1, 1] = 2
df2

BBB  CCC
alpha    1   11
gama     7    2
zeta    16    5

In [25]:
df2.iloc[:, 1] = 0
df2

BBB  CCC
alpha    1    0
gama     7    0
zeta    16    0